### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kingjotaro** [kingjotaro/woovi-jr#1]
- [x] recalcular parcelas no crédito e a tabela de parcelamento
- [ ] bug ao dar f5 em qualquer tela que contenha InstallmentPayments 
- [x] melhorar validação dos campos de credito
- [ ] adicionar todos os componentes no storybook
- [ ] criar componente de entrada dinâmica inicial
- [ ] adicionar i18n
